export enum EQueryKeys {
  GUARDIANS = "GUARDIANS",
  APPROVED_PROJECTS = "APPROVED_PROJECTS",
  APPROVED_CONTRACTS = "APPROVED_CONTRACTS",
  APPROVED_PROJECTS_BY_ID = "APPROVED_PROJECTS_BY_ID",
  PROPOSALS = "PROPOSALS",
  CONTRACT_ID_WHITELIST = "CONTRACT_ID_WHITELIST",
  PROPOSAL_BY_ID = "PROPOSAL_BY_ID",
  PROJECT_ID_BY_CONTRACT_ID = "PROJECT_ID_BY_CONTRACT_ID"
}