export enum EQueryKeys {
  GUARDIANS = "GUARDIANS",
  APPROVED_PROJECTS = "APPROVED_PROJECTS",
  APPROVED_CONTRACTS = "APPROVED_CONTRACTS",
  PROPOSALS = "PROPOSALS",
  CONTRACT_ID_WHITELIST = "CONTRACT_ID_WHITELIST"
}